/*

DROP TABLE  T_ZSO_CONSULTA    CASCADE CONSTRAINTS;
DROP TABLE  T_ZSO_AGENDAMENTO CASCADE CONSTRAINTS;
DROP TABLE  T_ZSO_PSICOLOGO   CASCADE CONSTRAINTS;
DROP TABLE  T_ZSO_PACIENTE    CASCADE CONSTRAINTS;
*/

CREATE TABLE T_ZSO_PSICOLOGO
(
    CD_PSICOLOGO    NUMBER(3)       NOT NULL,
    NM_PSICOLOGO    VARCHAR2(30)    NOT NULL,
    DS_EMAIL        VARCHAR(50)     NOT NULL,
    DS_SENHA        VARCHAR2(15)    NOT NULL,
    VL_HORA         NUMBER(3, 2)    NOT NULL,
    NR_RANKING      NUMBER(4)       NOT NULL,
    TX_DESC_PERFIL  VARCHAR2(300)   NULL,
    NR_TELEFONE     VARCHAR2(14)    NULL,
    NR_CPF          VARCHAR(14)     NOT NULL,
    DT_NASCIMENTO   DATE            NOT NULL
);

    ALTER TABLE T_ZSO_PSICOLOGO
ADD CONSTRAINT PK_ZSO_PSICOLOGO
PRIMARY KEY (CD_PSICOLOGO);

    ALTER TABLE T_ZSO_PSICOLOGO
ADD CONSTRAINT UN_ZSO_PSICOLOGO
               UNIQUE (NR_CPF);

DESCRIBE T_ZSO_PSICOLOGO;

CREATE TABLE T_ZSO_PACIENTE
(
    CD_PACIENTE                 NUMBER(3)       NOT NULL,
    NM_PACIENTE                 VARCHAR2(30)    NOT NULL,
    DS_EMAIL                    VARCHAR2(50)    NOT NULL,
    DS_SENHA                    VARCHAR2(15)    NOT NULL,
    NR_TELEFONE                 VARCHAR2(14)    NOT NULL,
    DS_HISTORICO_CONSULTAS      CLOB            NULL,
    NR_CPF                      VARCHAR2(14)    NOT NULL,
    DT_NASCIMENTO               DATE            NOT NULL
);

    ALTER TABLE T_ZSO_PACIENTE
ADD CONSTRAINT PK_ZSO_PACIENTE
    PRIMARY KEY (CD_PACIENTE);
    
    ALTER TABLE T_ZSO_PACIENTE
ADD CONSTRAINT UN_ZSO_PACIENTE
              UNIQUE (NR_CPF);


CREATE TABLE T_ZSO_AGENDAMENTO
(
    CD_AGENDAMENTO              NUMBER(3)       NOT NULL,
    CD_PACIENTE                 NUMBER(3)       NOT NULL,
    CD_PSICOLOGO                NUMBER(3)       NOT NULL,
    DT_CONSULTA                 DATE            NOT NULL,
    DT_HORA_CONSULTA            DATE            NOT NULL
);

    ALTER TABLE T_ZSO_AGENDAMENTO
ADD CONSTRAINT PK_ZSO_AGENDAMENTO
    PRIMARY KEY (CD_AGENDAMENTO);
    
            ALTER TABLE T_ZSO_AGENDAMENTO
ADD CONSTRAINT FK_ZSO_AGENDAMENTO_PACIENTE
                 FOREIGN KEY (CD_PACIENTE)
  REFERENCES T_ZSO_PACIENTE (CD_PACIENTE);

              ALTER TABLE T_ZSO_AGENDAMENTO
ADD CONSTRAINT FK_ZSO_AGENDAMENTO_PSICOLOGO
                 FOREIGN KEY (CD_PSICOLOGO)
 REFERENCES T_ZSO_PSICOLOGO (CD_PSICOLOGO);
 
CREATE TABLE T_ZSO_CONSULTA
(
    CD_CONSULTA                 NUMBER(3)       NOT NULL,
    CD_AGENDAMENTO              NUMBER(3)       NOT NULL,
    CD_PACIENTE                 NUMBER(3)       NOT NULL,
    CD_PSICOLOGO                NUMBER(3)       NOT NULL,
    VL_CONSULTA                 NUMBER(3, 2)    NOT NULL
);

    ALTER TABLE T_ZSO_CONSULTA
ADD CONSTRAINT PK_ZSO_CONSULTA
    PRIMARY KEY (CD_CONSULTA);
    
                    ALTER TABLE T_ZSO_CONSULTA
    ADD CONSTRAINT FK_ZSO_CONSULTA_AGENDAMENTO
                  FOREIGN KEY (CD_AGENDAMENTO)
REFERENCES T_ZSO_AGENDAMENTO (CD_AGENDAMENTO);

            ALTER TABLE T_ZSO_CONSULTA
ADD CONSTRAINT FK_ZSO_CONSULTA_PACIENTE
                 FOREIGN KEY (CD_PACIENTE)
  REFERENCES T_ZSO_PACIENTE (CD_PACIENTE);

              ALTER TABLE T_ZSO_CONSULTA
ADD CONSTRAINT FK_ZSO_CONSULTA_PSICOLOGO
                 FOREIGN KEY (CD_PSICOLOGO)
REFERENCES T_ZSO_PSICOLOGO (CD_PSICOLOGO);

DESCRIBE T_ZSO_CONSULTA;

COMMIT;
